### ISSUE TITLE
Cache directory issue

### ISSUE THREAD

**Issue by ogizanagi** [Elao/github-agile-dashboard#5]
```sh
⏳  Fetching issues...
fs.js:894
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '//usr/local/lib/node_modules/@elao/github-agile-dashboard/cache'
    at Object.fs.mkdirSync (fs.js:894:18)
    at fullPath.split.reduce (/usr/local/lib/node_modules/@elao/github-agile-dashboard/src/Loader/Cache.js:74:20)
    at Array.reduce (native)
    at Cache.ensureDirectoryExists (/usr/local/lib/node_modules/@elao/github-agile-dashboard/src/Loader/Cache.js:70:29)
    at Cache.load (/usr/local/lib/node_modules/@elao/github-agile-dashboard/src/Loader/Cache.js:38:14)
    at HttpLoader.load (/usr/local/lib/node_modules/@elao/github-agile-dashboard/src/Loader/HttpLoader.js:49:32)
    at new GithubAgileDashboard (/usr/local/lib/node_modules/@elao/github-agile-dashboard/src/GithubAgileDashboard.js:28:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/@elao/github-agile-dashboard/gad.js:31:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

Le problème est que à ma connaissance `/usr/local/lib/` n'est habituellement pas accessible en écriture par l'utilisateur, hors super user.

Plusieurs propositions d'emplacement de cache:
- le dossier utilisateur, avec un `.gad/cache` ? Pour récupérer le dossier utilisateur, utiliser la variable d'env `HOME` qui est généralement set un peu partout, y compris sous windows il me semble (ou simplement via https://nodejs.org/api/os.html#os_os_homedir).
- le "local app data" dans le dossier utilisateur:
    - Sous windows: `C:\Users\<username>\AppData\Local`
    - Sous OS X: `~/Library/Caches`
    - ...
    Mais il ne semble pas y avoir de solution générique pour l'obtenir, à part différentes variables d'env selon l'OS.
- simplement dans `/tmp` (removed à chaque reboot) ? https://nodejs.org/api/os.html#os_os_tmpdir

---

some refs: 
- https://stackoverflow.com/questions/11113974/what-is-the-cross-platform-way-of-obtaining-the-path-to-the-local-application-da
- https://nodejs.org/api/os.html
- https://stackoverflow.com/questions/19275776/node-js-how-to-get-the-os-platforms-user-data-folder

**Comment by chalasr** [comment]
I'd be for `.gad/cache`

**Comment by chalasr** [comment]
For the record, here is how /tmp works on OSX https://superuser.com/questions/187071/in-macos-how-often-is-tmp-deleted

**Comment by Tom32i** [comment]
@chalasr  `files that aren't accessed in three days are deleted from /tmp`
Could work for us...
